/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zbus_ZContext */

#ifndef _Included_net_zbus_ZContext
#define _Included_net_zbus_ZContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zbus_ZContext
 * Method:    construct
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_zbus_ZContext_construct
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_zbus_ZContext
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_zbus_ZContext_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
