/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zbus_Worker */

#ifndef _Included_net_zbus_Worker
#define _Included_net_zbus_Worker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zbus_Worker
 * Method:    construct
 * Signature: (Lnet/zbus/WorkerConfig;)V
 */
JNIEXPORT void JNICALL Java_net_zbus_Worker_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_zbus_Worker
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_zbus_Worker_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
